postgres databases not initialized?

root@linuxkit-025000000001:/app# python run.py -lc data/parent_child.new
Matching disabled, no matching data available
overwriting config _INDEXER_HOST old val= localhost new val= localhost
overwriting config _BROKER_HOST old val= localhost new val= localhost
overwriting config _INDEXER_HOST old val= localhost new val= localhost
overwriting config _BROKER_HOST old val= localhost new val= localhost
There are 6157 unique canonical affids.
Traceback (most recent call last):
  File "run.py", line 233, in <module>
    main()
  File "run.py", line 97, in main
    tasks.task_write_canonical_to_db(recs)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "/app/ADSAffil/tasks.py", line 42, in task_write_canonical_to_db
    app.write_canonical_to_db(recs)
  File "/app/ADSAffil/app.py", line 135, in write_canonical_to_db
    with self.session_scope() as session:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/adsputils/__init__.py", line 412, in session_scope
    raise Exception('DB not initialized properly, check: SQLALCHEMY_URL')
Exception: DB not initialized properly, check: SQLALCHEMY_URL

===========================================================================
